### PR TITLE
Replaced setTimeout with requestAnimationFrame

### PR DESCRIPTION
**Pull request by pwolaq**
So I finally found some spare time and went a step further and replaced `setTimeout` with `requestAnimationFrame` as previously suggested. 

I have removed `delay` parameter for now, but it is possible to implement it to throttle updates - please tell me what do you think about it :)

### CODE REVIEW

**Comment by MicheleBertoli** [comment]
This is awesome, thank you very much @pwolaq.

I'm happy to merge it but I was wondering how hard it is in you opinion to keep the `delay` prop (and avoid a breaking change).

**Comment by pwolaq** [comment]
I've implemented the `delay` prop, but also encountered some weird behaviour with tests - after I added a new test for `delay` prop some of the tests started to fail. 

I will try to fix it tommorow.

**Comment by MicheleBertoli** [comment]
You are the best, @pwolaq.

**Comment by pwolaq** [comment]
It turns out that I had to call `jest.clearAllTimers` after each test in order to prevent this weird behaviour. It should be ok now.

**Comment by MicheleBertoli** [comment]
🙌

**Pull request merged**
